describe("solomon.statusline", function()
  local statusline

  before_each(function()
    package.loaded["solomon.statusline"] = nil
    statusline = require("solomon.statusline")
    statusline.reset()
  end)

  describe("record_request", function()
    it("increments request count", function()
      assert.equals(0, statusline._request_count)
      statusline.record_request({ text = "test" })
      assert.equals(1, statusline._request_count)
      statusline.record_request({ text = "test2" })
      assert.equals(2, statusline._request_count)
    end)

    it("accumulates cost", function()
      statusline.record_request({ cost_usd = 0.01 })
      statusline.record_request({ cost_usd = 0.02 })
      assert.is_near(0.03, statusline._total_cost, 0.0001)
    end)

    it("tracks last model", function()
      statusline.record_request({ model = "claude-sonnet-4-6" })
      assert.equals("claude-sonnet-4-6", statusline._last_model)
      statusline.record_request({ model = "claude-opus-4-6" })
      assert.equals("claude-opus-4-6", statusline._last_model)
    end)

    it("handles missing fields gracefully", function()
      statusline.record_request({})
      assert.equals(1, statusline._request_count)
      assert.equals(0, statusline._total_cost)
      assert.is_nil(statusline._last_model)
    end)
  end)

  describe("reset", function()
    it("clears all tracked state", function()
      statusline.record_request({ cost_usd = 0.05, model = "test" })
      statusline.reset()
      assert.equals(0, statusline._total_cost)
      assert.equals(0, statusline._request_count)
      assert.is_nil(statusline._last_model)
    end)
  end)

  describe("component", function()
    it("returns a function", function()
      local comp = statusline.component()
      assert.is_function(comp)
    end)

    it("returns empty string when inactive", function()
      local comp = statusline.component()
      assert.equals("", comp())
    end)

    it("includes model name when set", function()
      statusline._last_model = "claude-sonnet-4-6-20250320"
      local comp = statusline.component()
      local result = comp()
      assert.truthy(result:find("sonnet%-4%-6%-20250320"))
    end)

    it("includes cost when tracked", function()
      statusline._total_cost = 0.042
      local comp = statusline.component()
      local result = comp()
      assert.truthy(result:find("$0.042", 1, true))
    end)
  end)

  describe("condition", function()
    it("returns a function", function()
      local cond = statusline.condition()
      assert.is_function(cond)
    end)

    it("returns false when no requests made", function()
      local cond = statusline.condition()
      assert.is_false(cond())
    end)

    it("returns true after a request", function()
      statusline.record_request({})
      local cond = statusline.condition()
      assert.is_true(cond())
    end)
  end)

  describe("lualine", function()
    it("returns a table with component and cond", function()
      local ll = statusline.lualine()
      assert.is_table(ll)
      assert.is_function(ll[1])
      assert.is_function(ll.cond)
    end)
  end)
end)
